services:
  kong:
    build: .
    extra_hosts:
      - "host.docker.internal:host-gateway" # for linux
    environment:
      KONG_PLUGINS: bundled,pheno_ui_maps
      KONG_NGINX_MAIN_ENV: "SALESFORCE_API_TOKEN"
      SALESFORCE_API_TOKEN: $SALESFORCE_API_TOKEN
    volumes:
      - "./config:/kong/declarative/"
      - "./plugins/maps:/usr/local/share/lua/5.1/kong/plugins/pheno_ui_maps"
      - "./plugins/maps_configs:/pheno_ui_maps_configs/"
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8001:8001"
      - "8444:8444"
      - "8002:8002"
      - "8445:8445"
      - "8003:8003"
      - "8004:8004"